Add fossa analyze

diff --git a/.github/workflows/fossa-gradle.yml b/.github/workflows/fossa-gradle.yml
--- a/.github/workflows/fossa-gradle.yml
+++ b/.github/workflows/fossa-gradle.yml
@@ -60,32 +60,32 @@ jobs:
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/orgs/$ORG/properties/values \
             -d '{"repository_names":["'"${REPO##*/}"'"],"properties":[{"property_name":"hasFossaTargets","value":"'"${{ steps.fossa-list-targets.outputs.HAS_FOSSA_TARGETS }}"'"}]}'
-      # - id: fossa-analyze
-      #   name: Run fossa analyze
-      #   if: ${{ steps.fossa-list-targets.outputs.HAS_FOSSA_TARGETS == 'True'}}
-      #   run: |
-      #     export ANALYZE_OUT_FILE=${{ runner.temp }}/analyze_out.txt
-      #     export ANALZYE_ERR_FILE=${{ runner.temp }}/analyze_err.txt
-      #     fossa analyze --policy='New Relic Public Github' 1>$ANALYZE_OUT_FILE 2>$ANALZYE_ERR_FILE
-      #     if [[ $(grep -i "error" $ANALYZE_ERR_FILE | wc -l) -gt 0 ]]
-      #     then
-      #         echo "::error::fossa analyze ran with errors."
-      #         cat $ANALYZE_ERR_FILE
-      #         echo "FOSSA_ANALYZE_RESULT=Error" >> "$GITHUB_OUTPUT"
-      #     else
-      #         cat $ANALYZE_OUT_FILE
-      #         echo "FOSSA_ANALYZE_RESULT=Success" >> "$GITHUB_OUTPUT"
-      #     fi
-      # - name: Set fossaAnalyzeResult custom property
-      #   run: |
-      #     curl -L \
-      #       -X PATCH \
-      #       -H "Accept: application/vnd.github+json" \
-      #       -H "Authorization: Bearer $ORG_ADMIN_PAT" \
-      #       -H "X-GitHub-Api-Version: 2022-11-28" \
-      #       https://api.github.com/orgs/$ORG/properties/values \
-      #       -d '{"repository_names":["'"${REPO##*/}"'"],"properties":[{"property_name":"fossaAnalyzeResult","value":"'"${{ steps.fossa-analyze.outputs.FOSSA_ANALYZE_RESULT }}"'"}]}'
-      # - name: Exit
-      #   if: ${{ steps.fossa-list-targets.outputs.HAS_FOSSA_TARGETS == 'Error' || steps.fossa-analyze.outputs.FOSSA_ANALYZE_RESULT == 'Error' }}
-      #   run: exit 1
+      - id: fossa-analyze
+        name: Run fossa analyze
+        if: ${{ steps.fossa-list-targets.outputs.HAS_FOSSA_TARGETS == 'True'}}
+        run: |
+          export ANALYZE_OUT_FILE=${{ runner.temp }}/analyze_out.txt
+          export ANALZYE_ERR_FILE=${{ runner.temp }}/analyze_err.txt
+          fossa analyze --policy='New Relic Public Github' 1>$ANALYZE_OUT_FILE 2>$ANALZYE_ERR_FILE
+          if [[ $(grep -i "error" $ANALYZE_ERR_FILE | wc -l) -gt 0 ]]
+          then
+              echo "::error::fossa analyze ran with errors."
+              cat $ANALYZE_ERR_FILE
+              echo "FOSSA_ANALYZE_RESULT=Error" >> "$GITHUB_OUTPUT"
+          else
+              cat $ANALYZE_OUT_FILE
+              echo "FOSSA_ANALYZE_RESULT=Success" >> "$GITHUB_OUTPUT"
+          fi
+      - name: Set fossaAnalyzeResult custom property
+        run: |
+          curl -L \
+            -X PATCH \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer $ORG_ADMIN_PAT" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/orgs/$ORG/properties/values \
+            -d '{"repository_names":["'"${REPO##*/}"'"],"properties":[{"property_name":"fossaAnalyzeResult","value":"'"${{ steps.fossa-analyze.outputs.FOSSA_ANALYZE_RESULT }}"'"}]}'
+      - name: Exit
+        if: ${{ steps.fossa-list-targets.outputs.HAS_FOSSA_TARGETS == 'Error' || steps.fossa-analyze.outputs.FOSSA_ANALYZE_RESULT == 'Error' }}
+        run: exit 1
 
