Update fossa.yml

diff --git a/.github/workflows/fossa.yml b/.github/workflows/fossa.yml
--- a/.github/workflows/fossa.yml
+++ b/.github/workflows/fossa.yml
@@ -20,26 +20,40 @@ jobs:
 
     steps:  
       - uses: actions/checkout@v3
-      - name: Run fossa 
+      - id: fossa-list-targets
+        name: Run fossa list-targets 
         run: |
           curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
           list_targets_output="$(fossa list-targets 2>&1)" 
           printf -- "%s\n" "$list_targets_output"
 
-          if [[ echo $list_targets_output | grep 'Error' ]]
+          list_targets_output="$(fossa list-targets 2>&1)" 
+          printf -- "%s\n" "$list_targets_output"
+          
+          if [[ $(echo $list_targets_output | grep "Error" | wc -l) -gt 0 ]]
           then
-              export HAS_FOSSA_TARGETS="Error"
-          elif [[ echo $list_targets_output | grep 'Found target' ]]
+              "HAS_FOSSA_TARGETS=Error" >> "$GITHUB_OUTPUT"
+          elif [[ $(echo $list_targets_output | grep "Found target" | wc -l) -gt 0 ]]
+          then
               fossa analyze
-              export HAS_FOSSA_TARGETS="True"
+              "HAS_FOSSA_TARGETS=True" >> "$GITHUB_OUTPUT"
           else
               printf -- "Fossa did not find any analysis targets.\n"
-              export HAS_FOSSA_TARGETS="False"
+              "HAS_FOSSA_TARGETS=False" >> "$GITHUB_OUTPUT"
           fi
+      - name: Set hasFossaTargets custom property
+        run: |
           curl -L \
             -X PATCH \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $ORG_ADMIN_PAT" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/orgs/$ORG/properties/values \
-            -d '{"repository_names":["'"${REPO##*/}"'"],"properties":[{"property_name":"hasFossaTargets","value":"'"${HAS_FOSSA_TARGETS}"'"}]}'
+            -d '{"repository_names":["'"${REPO##*/}"'"],"properties":[{"property_name":"hasFossaTargets","value":"'"${{ steps.fossa-list-targets.outputs.HAS_FOSSA_TARGETS }}"'"}]}'
+      - name: Fail if fossa list-targets had an error
+        if: ${{ steps.fossa-list-targets.outputs.HAS_FOSSA_TARGETS == 'Error'}}
+        run: exit 1
+      - name: Run fossa analyze
+        if: ${{ steps.fossa-list-targets.outputs.HAS_FOSSA_TARGETS == 'True'}}
+        run: fossa analyze
+
